version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "[INFO] Installing pnpm..."
      - npm install -g pnpm@11.8.0
      - echo "[INFO] Installing dependencies..."
      - pnpm install --frozen-lockfile

  pre_build:
    commands:
      - echo "[INFO] Running tests..."
      - pnpm test
      - echo "[INFO] Tests passed."

      - echo "[INFO] Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - REPOSITORY_URI=${ECR_REPOSITORY_URI}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

      - echo "[INFO] Logging in to Docker Hub..."
      - DOCKER_USERNAME=$(aws ssm get-parameter --name /dockerhub/username --query 'Parameter.Value' --output text)
      - DOCKER_PASSWORD=$(aws ssm get-parameter --name /dockerhub/password --with-decryption --query 'Parameter.Value' --output text)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "[INFO] Successfully logged in to Docker Hub"

  build:
    commands:
      - echo "[INFO] Pulling the cached Docker image..."
      - docker pull $REPOSITORY_URI:latest || true

      - echo "[INFO] Building Docker image..."
      - IMAGES_FOUND=$(aws ecr describe-images --repository-name $(basename $REPOSITORY_URI) --region $AWS_DEFAULT_REGION 2>/dev/null | jq '.imageDetails | length')
      - |
        if [[ "$IMAGES_FOUND" -gt 0 ]]; then
          echo "[INFO] Cached image found, building with cache..."
          docker build --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:latest .
        else
          echo "[WARNING] No cached image found, proceeding without cache."
          docker build -t $REPOSITORY_URI:latest .
        fi
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo "[INFO] Docker image built successfully!"

  post_build:
    commands:
      - echo "[INFO] Pushing the Docker image..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "[INFO] Docker image pushed successfully!"
      - echo '[{"name":"'$CONTAINER_NAME'","imageUri":"'$REPOSITORY_URI:$IMAGE_TAG'"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
